version: '3'
services:  
  api:    
    build: ./api    
    container_name: api_backend    
    ports:      
      - '4001:4001'    
    volumes:     
      - ./api:/app      
      # - ./app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '4000:3000'
    volumes:
      - ./client:/app
      # - ./app/node_modules
    stdin_open: true
    tty: true
